import localFont from "next/font/local";
import "./globals.css";

const dmSans = localFont({
  src: "./fonts/DMSans-Regular.ttf",
});

export const metadata = {
  title: "Object Detection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
